name: stage_badgebuddy
services:
  discord-bot-1:
    container_name: discord-bot-1_stage-badgebuddy
    image: amaredeus/badgebuddy-discord-bot:next
    restart: always
    networks:
      - stage_server
    environment:
      DOTENV_KEY: ${DOTENV_KEY}
    volumes:
      - ./logs:/app/logs
      - type: bind
        source: /run/redis-badge-buddy/redis-server-badge-buddy.sock
        target: /app/redis/redis.sock

networks:
  stage_server:
    external: true
