name: prod_badgebuddy
services:
  discord-bot-1:
    container_name: discord-bot-1_prod-badgebuddy
    image: badgebuddy/discord-bot:latest
    restart: always
    networks:
      - prod_server
    environment:
      DOTENV_KEY: ${DOTENV_KEY}
    volumes:
      - ./logs:/app/logs
      - type: bind
        source: /run/redis-badge-buddy/redis-server-badge-buddy.sock
        target: /app/redis/redis.sock

networks:
  prod_server:
    external: true
