name: local_badgebuddy
services:
  discord-bot-1:
    container_name: local_badgebuddy-discord-bot-1
    depends_on:
      - redis
    build:
      context: .
    env_file:
      - .env
    environment:
      BADGE_BUDDY_API_HOST: api-1_local-badgebuddy
    networks:
      - local_server
    volumes:
      - ./logs:/app/logs

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    networks:
      - local_server

networks:
  local_server:
    external: true
