ARG NODE_VERSION

FROM oven/bun:1.0.0 as bun
WORKDIR /app
COPY . /app/
RUN bun install
RUN bun run nest build

FROM node:${NODE_VERSION}-alpine AS base
LABEL description="Node processor for badge-buddy-bot"

WORKDIR /app
COPY --from=bun /app/node_modules /app/node_modules
COPY --from=bun /app/dist /app/dist

COPY CHANGELOG.md /app/dist/
COPY LICENSE.md /app/dist/
COPY README.md /app/dist/

CMD ["node", "dist/main"]
