export const ENV_BADGEBUDDY_API_HOST = 'BADGEBUDDY_API_HOST' as const;
export const ENV_BADGEBUDDY_API_CLIENT_ID = 'BADGEBUDDY_API_CLIENT_ID' as const;
export const ENV_BADGEBUDDY_API_CLIENT_SECRET =
  'BADGEBUDDY_API_CLIENT_SECRET' as const;
