export const ENV_BADGE_BUDDY_API_HOST = 'BADGE_BUDDY_API_HOST' as const;
export const ENV_AUTH_DISCORD_BOT_CLIENT_ID = 'AUTH_DISCORD_BOT_CLIENT_ID' as const;
export const ENV_AUTH_DISCORD_BOT_CLIENT_SECRET = 'AUTH_DISCORD_BOT_CLIENT_SECRET' as const;
